### PR TITLE
Profile branch

### PR DESCRIPTION
**Pull request by nyananu**
This PR replaces and addresses the issues with the previous Profile Pr (#68 )

Changes in this PR:
1) changes occurrences of 'delete profile' to 'delete account' @phreid 
2) Modals close after the information is submitted @phreid 
3) items show up on 'my items' page @imogenem 
4) reset button clears form input @imogenem 

Thanks for your help guys!

### CODE REVIEW

**Comment by phreid** [comment]
In this branch, the edit profile form isn't pre-filled with the user's data. 

profileUpdate branch: 

```
EditUserForm.jsx

const [username, setUsername] = useState(currentUser.username)
const [password, setPassword] = useState(currentUser.password)
const [bio, setBio] = useState(currentUser.bio)
const [email, setEmail] = useState(currentUser.email)
const [location, setLocation] = useState(currentUser.location)
```

profileBranch branch:

```
ProfilePage.jsx

const [username, setUsername] = useState('')
const [password, setPassword] = useState('')
const [bio, setBio] = useState('')
const [email, setEmail] = useState('')
const [location, setLocation] = useState('')
```

And if the form is submitted with an empty field, it overwrites what's in the database with an empty field.

**Comment by nyananu** [comment]
@phreid I updated the edit user form to not accept any blank value so that the DB isn't overwritten. I also made sure that the Edit User form is pre-filled with the user's data.
 
To make my code cleaner, I abstracted out both the Edit User and Delete Account forms into different components. The downside of this is that the _EditUserForm will not close when the user clicks 'submit'_. It will only close if:
- the cross is clicked at the top right
- the user clicks outside the modal
I don't think this is a major issue, and I can take it up in the next sprint.

Also cleaned up the appearance of the profile page and respective modals.

This PR doesn't have any conflicts with dev, and it seems good to go. Waiting on approval to merge.

**Review by imogenem — APPROVED** [review]
The edit profile modal isn't closing for me when I submit the changes, but I think we can fix that in the next sprint since everything else works great.

**Comment by nyananu** [comment]
@imogenem  yep, that's what I mentioned (I'll edit my comment to make it clear). As of now, the profile modal will not close when the submit button is clicked. It will only close when the cross is clicked (on the top right) or when you click outside the modal. Because the modal show logic is on the profile component and the actual submit form logic in the edit user component, the submit button is giving me a hard time tying in with the close modal logic. I will fix this in the next sprint.

**Comment by phreid** [comment]
@nyananu Not sure what the issue is exactly with closing on submit, but there are working examples in EditCardModal and EditRatingModal in case you haven't seen them.

**Comment by nyananu** [comment]
Yup, I have seen those examples. I was working through them and trying to pass the show and hide parameters accordingly, but because of the way my logic for modals is abstracted right now, it wasn't working as expected. I'll fix this up in the upcoming sprint.

**Pull request merged**
