### PR TITLE
Navbar and Marketplace page

### PR DESCRIPTION
**Pull request by cailors**
Screen Shot 2022-06-22 at 5 40 54 PM
Notes:
1. <NavBra currPage="">, props needed.
2. Borders showed in Marketplace page are for showing, will be removed once finished.
3. Changes in App.js and AddItemPage.js are necessary, keep them when merging

### CODE REVIEW

**Comment by phreid** [comment]
Can you add screenshots when you get a chance?

**Comment by phreid** [comment]
This should be merging into the `dev` branch, not `main`.

**Comment by phreid** [comment]
This branch is missing a bunch of commits that were merged into `dev`, including the fixes to the linter config. highly recommend pulling in those changes

**Review by phreid — CHANGES_REQUESTED** [review]
This branch is missing a bunch of commits that were merged into `dev`, including the fixes to the linter config. Those changes should be pulled into this branch.

**Review by phreid — CHANGES_REQUESTED** [review]
Sorry if I missed some discussion about this today, but the navbar doesn't need to use redux, passing props, etc. to work with `react-router` and show the active link. 

See [this branch](https://github.com/nyananu/somethingBorrowed/tree/navbar-no-redux) for an example of a simple responsive navbar, as a baseline that can be extended and styled.

**Comment by cailors** [comment]
> Sorry if I missed some discussion about this today, but the navbar doesn't need to use redux, passing props, etc. to work with `react-router` and show the active link.
> 
> See [this branch](https://github.com/nyananu/somethingBorrowed/tree/navbar-no-redux) for an example of a simple responsive navbar, as a baseline that can be extended and styled.

The props are used to change color of the text that represents the

**Pull request closed without merging**
